# Generated by Django 4.2 on 2025-08-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='id',
            new_name='restaurant_id',
        ),
    ]
