# Generated by Django 4.2 on 2025-08-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_id_restaurant_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='large_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='medium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
