# Generated by Django 4.2 on 2025-07-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_representative_alter_restaurant_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='email',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='position',
        ),
        migrations.AddField(
            model_name='representative',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_rep_images/'),
        ),
    ]
