# Generated by Django 4.2 on 2025-07-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_representative_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representative',
            old_name='representative',
            new_name='photo',
        ),
    ]
