# Generated by Django 4.2 on 2025-07-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_rider_shifttype_ridershift'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='rider_profiles/'),
        ),
    ]
