# Generated by Django 4.2 on 2025-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rider_address_rider_date_of_birth_rider_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='rider_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
