# Generated by Django 4.2 on 2025-07-21 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_rider_rider_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=restaurants.models.generate_order_id, editable=False, max_length=10, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pickoff', 'Pickoff'), ('dropoff', 'Dropoff'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.rider')),
            ],
        ),
    ]
