# Generated by Django 4.2 on 2025-07-27 15:34

from django.db import migrations, models
import django.db.models.deletion
import franchise.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('representative_image', models.ImageField(blank=True, null=True, upload_to='representatives/')),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_id', models.CharField(default=franchise.models.generate_franchise_id, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('business_license', models.CharField(max_length=100)),
                ('owner_nid', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('franchise_image', models.ImageField(blank=True, null=True, upload_to='franchise/')),
                ('overall_rating', models.CharField(default='0.0', max_length=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='franchise.representative')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(default=franchise.models.generate_branch_id, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('business_license', models.CharField(max_length=100)),
                ('owner_nid', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('working_period', models.CharField(max_length=255)),
                ('large_option', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('restaurant_image', models.ImageField(blank=True, null=True, upload_to='branches/')),
                ('rating', models.CharField(default='0.0', max_length=5)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='franchise.franchise')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='franchise.representative')),
            ],
        ),
    ]
