# Generated by Django 4.2 on 2025-07-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/branch/'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='owner_nid',
            field=models.FileField(blank=True, null=True, upload_to='nid/branch/'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/franchise/'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='owner_nid',
            field=models.FileField(blank=True, null=True, upload_to='nid/franchise/'),
        ),
    ]
